const ordenCreada = { __v: 0,
    id: '8',
    or: '',
    name: 'german',
    last_name: 'angarita',
    kiolometers: '9000',
    nit: '1018413450',
    email: 'germanadolfoangarita@gmail.com',
    telephone: '3007410908',
    plate: 'ASD1231',
    vin: 'kojejeurjdujdjdju',
    model: 'optra',
    brand: 'chevrolet',
    year: '2019',
    accountId: '5bb429a0ca0702060e3ab33f',
    centerId: '5bb42a01ca0702060e3ab340',
    center_code: 'CS000',
    account_code: 'AC001',
    account: 'DEMO COLOMBIA',
    center: 'DEMO',
    nit_account: '9000000001',
    logo: '',
    address_account: 'Carrera 27 No 30-67',
    city_account: 'BOGOTÁ D.C.',
    country_account: 'Colombia',
    telephone_account: '3007410908',
    list: 
     { createdUp: '2019-12-11T04:17:28.705Z',
       advanceValue: 0,
       __v: 0,
       advanceVisible: true,
       account_code: 'AC001',
       description: 'Listado Demo',
       key: 'AC001DEMO',
       list: 'DEMO',
       _id: '5df06dd89fa4e2033e08695d' },
    _id: '5e4c8dd3d10499472bf31589',
    moreInfo: [],
    reception: false,
    customer_response: false,
    send_to_customer: false,
    mo_ban: 0,
    parts_ban: 0,
    total_ban: 0,
    mo_approve: 0,
    parts_approve: 0,
    total_approve: 0,
    mo: 0,
    parts: 0,
    total: 0,
    process:[ { checkList: [Array],
         advanceValue: 0,
         index: 1,
         notifyCustomer: false,
         weight: null,
         description: 'Inicio del proceso, recepción',
         icon: '<i class="fas fa-hands"></i>',
         name: 'Inicio del proceso',
         id: '5df06dfc9fa4e2033e08695e' },
       { checkList: [Array],
         advanceValue: 0,
         index: 2,
         notifyCustomer: false,
         weight: null,
         description: 'Desarme del artefacto',
         icon: '<i class="fas fa-glasses"></i>',
         name: 'DESARME',
         id: '5df07d87aff4ae0b2eca3ee4' } ],
    notify: { pending: 0, view: false },
    approval_info: { date: '', status: 'pending' },
    quotation_info: { date: '', status: 'pending' },
    evaluation_info: { date: '', status: 'pending' },
    reception_info: { date: '', status: 'process' },
    status: 'reception',
    notes: [],
    create: '2020-02-19T01:22:27.050Z' }